[0m17:18:54.462991 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109438c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a0f3670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a0f3ac0>]}


============================== 17:18:54.466082 | 81c2ac6c-c8ca-4ade-91e5-9a3c2a1fe366 ==============================
[0m17:18:54.466082 [info ] [MainThread]: Running with dbt=1.9.6
[0m17:18:54.466447 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/alexfoo/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbt_olist', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:18:54.477218 [debug] [MainThread]: Starter project path: /Users/alexfoo/miniconda3/envs/elt/lib/python3.10/site-packages/dbt/include/starter_project
[0m17:18:54.482614 [info ] [MainThread]: 
Your new dbt project "dbt_olist" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:18:54.482852 [info ] [MainThread]: Setting up your profile.
[0m17:21:22.251738 [info ] [MainThread]: Profile dbt_olist written to /Users/alexfoo/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m17:21:22.256146 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 147.8688, "process_in_blocks": "0", "process_kernel_time": 0.30122, "process_mem_max_rss": "211304448", "process_out_blocks": "0", "process_user_time": 2.187698}
[0m17:21:22.257288 [debug] [MainThread]: Command `dbt init` succeeded at 17:21:22.257050 after 147.87 seconds
[0m17:21:22.258394 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109438c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x123175420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x123177f70>]}
[0m17:21:22.259232 [debug] [MainThread]: Flushing usage events
[0m17:21:23.422750 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:33:40.808325 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107af15d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087bb160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087bad10>]}


============================== 17:33:40.811553 | 552bdd1a-3e6a-4211-82a4-e5314889c31b ==============================
[0m17:33:40.811553 [info ] [MainThread]: Running with dbt=1.9.6
[0m17:33:40.811924 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/alexfoo/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbt_olist', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:33:40.820774 [info ] [MainThread]: A project called dbt_olist already exists here.
[0m17:33:40.822483 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.066294126, "process_in_blocks": "0", "process_kernel_time": 0.119309, "process_mem_max_rss": "125681664", "process_out_blocks": "0", "process_user_time": 1.590275}
[0m17:33:40.822771 [debug] [MainThread]: Command `dbt init` succeeded at 17:33:40.822705 after 0.07 seconds
[0m17:33:40.822992 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107af15d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087babf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087ba200>]}
[0m17:33:40.823203 [debug] [MainThread]: Flushing usage events
[0m17:33:42.070667 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:44:06.527265 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072e8790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f9ef20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f9f370>]}


============================== 17:44:06.530607 | 9a05449f-8d9f-4ee5-9173-17ad6162919f ==============================
[0m17:44:06.530607 [info ] [MainThread]: Running with dbt=1.9.6
[0m17:44:06.530984 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/alexfoo/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt seed', 'send_anonymous_usage_stats': 'True'}
[0m17:44:06.531346 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/alexfoo/Documents/NTU_DSAI/5m-data-m2-project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:44:06.533051 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.058307543, "process_in_blocks": "0", "process_kernel_time": 0.119651, "process_mem_max_rss": "126173184", "process_out_blocks": "0", "process_user_time": 1.595314}
[0m17:44:06.533332 [debug] [MainThread]: Command `dbt seed` failed at 17:44:06.533272 after 0.06 seconds
[0m17:44:06.533556 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072e8790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f82830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f9f610>]}
[0m17:44:06.533762 [debug] [MainThread]: Flushing usage events
[0m17:44:07.783869 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:06:18.544387 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1057e5d80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10650f160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10650ed10>]}


============================== 16:06:18.547983 | 2cd88fa7-49f3-4f04-8359-f375a94942f8 ==============================
[0m16:06:18.547983 [info ] [MainThread]: Running with dbt=1.9.6
[0m16:06:18.548376 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/alexfoo/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m16:06:18.559837 [info ] [MainThread]: dbt version: 1.9.6
[0m16:06:18.560070 [info ] [MainThread]: python version: 3.10.18
[0m16:06:18.560262 [info ] [MainThread]: python path: /Users/alexfoo/miniconda3/envs/elt/bin/python3.10
[0m16:06:18.560442 [info ] [MainThread]: os info: macOS-15.6.1-arm64-arm-64bit
[0m16:06:22.182584 [info ] [MainThread]: Using profiles dir at /Users/alexfoo/.dbt
[0m16:06:22.182913 [info ] [MainThread]: Using profiles.yml file at /Users/alexfoo/.dbt/profiles.yml
[0m16:06:22.183106 [info ] [MainThread]: Using dbt_project.yml file at /Users/alexfoo/Documents/NTU_DSAI/5m-data-m2-project/dbt_project.yml
[0m16:06:22.183330 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m16:06:22.183596 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 3.6939762, "process_in_blocks": "0", "process_kernel_time": 0.347898, "process_mem_max_rss": "241270784", "process_out_blocks": "0", "process_user_time": 2.387602}
[0m16:06:22.183828 [debug] [MainThread]: Command `dbt debug` failed at 16:06:22.183782 after 3.69 seconds
[0m16:06:22.184028 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1057e5d80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12423d240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12423d000>]}
[0m16:06:22.184245 [debug] [MainThread]: Flushing usage events
[0m16:06:23.284769 [debug] [MainThread]: An error was encountered while trying to flush usage events
